"""
AI Trend Fetcher — Core automation script.

This script is the main entry point for fetching trending AI videos
and generating a markdown report. It can be run:
  1. Directly: python src/get_trends.py
  2. Via slash command: /get-ai-trends (in Claude Code)
  3. Via GitHub Action: daily-trends.yml

Currently a stub — the real fetching is done through the MCP server
when Claude Code orchestrates the workflow via the slash command.
"""

import json
from datetime import date
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "output"


def generate_report(videos: list[dict], report_date: date | None = None) -> str:
    """Generate a markdown report from a list of video dicts."""
    report_date = report_date or date.today()
    lines = [
        f"# AI Trends — {report_date.isoformat()}",
        "",
        "## Top Trending Videos",
        "",
        "| # | Title | Channel | Views | Link |",
        "|---|-------|---------|-------|------|",
    ]

    for i, video in enumerate(videos, 1):
        url = f"https://youtube.com/watch?v={video['video_id']}"
        views = f"{video['views']:,}"
        lines.append(f"| {i} | {video['title']} | {video['channel']} | {views} | [Watch]({url}) |")

    lines.extend([
        "",
        "## Highlights",
        "",
    ])

    for video in videos[:3]:
        lines.append(f"- **{video['title']}** ({video['channel']}): {video['description'][:100]}")

    lines.extend([
        "",
        "---",
        "*Generated by AI Trend Aggregator*",
    ])

    return "\n".join(lines)


def save_report(content: str, report_date: date | None = None) -> Path:
    """Save a markdown report to the output directory."""
    report_date = report_date or date.today()
    OUTPUT_DIR.mkdir(exist_ok=True)
    path = OUTPUT_DIR / f"{report_date.isoformat()}-trends.md"
    path.write_text(content)
    return path


if __name__ == "__main__":
    # Stub: load mock data and generate a sample report
    from src.mcp_youtube.server import MOCK_VIDEOS

    report = generate_report(MOCK_VIDEOS)
    path = save_report(report)
    print(f"Report saved to {path}")
