"""
AI Trend Fetcher — Core automation script.

This script is the main entry point for generating a markdown report
from video data. It can be run:
  1. Directly: python src/get_trends.py (generates sample report)
  2. Via slash command: /get-ai-trends (Claude Code fetches via MCP, then formats)
  3. Via GitHub Action: daily-trends.yml
"""

from datetime import date
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "output"

SAMPLE_VIDEOS = [
    {
        "video_id": "abc123",
        "title": "Sample: GPT-5 Is Here",
        "channel": "AI Explained",
        "views": 450000,
        "description": "A deep dive into the latest GPT-5 capabilities and benchmarks...",
    },
    {
        "video_id": "def456",
        "title": "Sample: Building AI Agents That Work",
        "channel": "Fireship",
        "views": 320000,
        "description": "Let's build a real AI agent from scratch using the latest frameworks...",
    },
]


def generate_report(videos: list[dict], report_date: date | None = None) -> str:
    """Generate a markdown report from a list of video dicts."""
    report_date = report_date or date.today()
    lines = [
        f"# AI Trends — {report_date.isoformat()}",
        "",
        "## Top Trending Videos",
        "",
        "| # | Title | Channel | Views | Link |",
        "|---|-------|---------|-------|------|",
    ]

    for i, video in enumerate(videos, 1):
        url = f"https://youtube.com/watch?v={video['video_id']}"
        views = f"{video['views']:,}"
        lines.append(f"| {i} | {video['title']} | {video['channel']} | {views} | [Watch]({url}) |")

    lines.extend(["", "## Highlights", ""])

    for video in videos[:3]:
        lines.append(f"- **{video['title']}** ({video['channel']}): {video['description'][:100]}")

    lines.extend(["", "---", "*Generated by AI Trend Aggregator*"])

    return "\n".join(lines)


def save_report(content: str, report_date: date | None = None) -> Path:
    """Save a markdown report to the output directory."""
    report_date = report_date or date.today()
    OUTPUT_DIR.mkdir(exist_ok=True)
    path = OUTPUT_DIR / f"{report_date.isoformat()}-trends.md"
    path.write_text(content)
    return path


if __name__ == "__main__":
    report = generate_report(SAMPLE_VIDEOS)
    path = save_report(report)
    print(f"Sample report saved to {path}")
